### PR TITLE
Allow publisherKey to contain object rather then path to file containing that object

### PR DESCRIPTION
**Pull request by slepic**
Hi,

we are using your app inmaybe a bit unexpected manner. We basically don't call your command, instead we reimplement it so it loads all its config from env vars rather then a file.

```
const fs = require('fs');
const reviewme = require('@trademe/reviewme');

const config = {
	slackHook: process.env.SLACK_HOOK_URL,
	verbose: process.env.REVIEWME_VERBOSE === 'yes',
	dryRun: process.env.REVIEWME_DRY_RUN === 'yes',
	interval: parseInt(process.env.REVIEWME_INTERVAL || '300'),
	apps: [],
}

if (process.env.IOS_APP_ID) {
	config.apps.push({
		appId: process.env.IOS_APP_ID,
		regions: false,
	})
}

if (process.env.ANDROID_APP_ID && process.env.ANDROID_KEY_JSON) {
	const keyPath = '/app/android.key.json'
	fs.writeFileSync(keyPath, process.env.ANDROID_KEY_JSON);
	config.apps.push({
		appId: process.env.ANDROID_APP_ID,
		publisherKey: keyPath,
	})
}

reviewme.start(config);
```

with this change I can now do this instead:

```
if (process.env.ANDROID_APP_ID && process.env.ANDROID_KEY_JSON) {
	config.apps.push({
		appId: process.env.ANDROID_APP_ID,
		publisherKey: JSON.parse(process.env.ANDROID_KEY_JSON),
	})
}
```

and so I avoid storing anything (and especially private credentials) in filesystem in a temporary file.

Another use case could be to include the publisherKey json directly in the config.json of the app. Not sure who and why would do this, but why not I guess.

### CODE REVIEW

**Comment by slepic** [comment]
Hi @josh-burton ,
thanks for the approval. Can you please also merge, tag and release? Or is there any blocker? Do you want me to update readme?

**Comment by josh-burton** [comment]
I'll leave it up to @jamiesanson to merge and release as I don't have the required permissions.

**Comment by jamiesanson** [comment]
Looks good to me! It seems I also no longer have the required permissions to merge + publish new versions. @rwjc are you able to help out?

**Comment by rwjc** [comment]
Doesn't look like I have the permission either. @rnpy?

**Pull request merged**
