### PR TITLE
Add version option to print version info

### PR DESCRIPTION
**Pull request by PeterDaveHello**
This help confirm which version has been installed and would be running.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Hi @athornz, would you like to help review this PR :smile: Many thanks!

**Comment by PeterDaveHello** [comment]
Hi @athornz, would you like to help review this PR smile Many thanks!

**Comment by PeterDaveHello** [comment]
@jamiesanson not sure if you can help review, just ping for a chance, thanks.

**Comment by jamiesanson** [comment]
Cheers for the contribution @PeterDaveHello!

**Comment by PeterDaveHello** [comment]
Thanks @athornz & @jamiesanson , please also help take a look at two other pull requests, thank you both :bow:

**Pull request merged**
