### PR TITLE
Add a basic Dockerfile w/ .dockerignore

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Simply build it with:
```
docker build --build-arg ReviewMeVersion=version -t reviewme:version .
```

Or without specifying build argument `ReviewMeVersion`:
```
docker build reviewme:version .
```
by defauly it'll use the latest published v2 of ReviewMe

After the building, use it with:
```
docker run -v $PWD/myappsconfig.json:/config.json reviewme:version reviewme /config.json
```

Don't forget to replace `version` with an real version number like: 2.0.2

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Hi @athornz, would you like to help review this PR :smile: Many thanks!

**Comment by PeterDaveHello** [comment]
Hi @jamiesanson @athornz, would you help review this PR? Thanks.

**Comment by PeterDaveHello** [comment]
Hi @jamiesanson @athornz, would you help review this PR? Thanks.

**Comment by jamiesanson** [comment]
Sorry for the delay @PeterDaveHello!

**Comment by PeterDaveHello** [comment]
Thank you both!

**Pull request merged**
